### ISSUE TITLE
Spout Gravity persists

### ISSUE THREAD

**Issue by ghost** [kitskub/bSpace#88] opened 2012-01-02 18:28 UTC
Hi. On my world i use Inception to layer the worlds. I noticed that if inception teleports me from bSpace to the world below, the low gravity will stay. It stays until i die or relog.

**Comment by iffa** [comment] 2012-01-03 00:40
Could be

**Comment by kitskub** [comment] 2012-01-03 01:52
What version of inception are you using?

**Comment by ghost** [comment] 2012-01-03 02:25
it says Version 1.04dev0.5 in console

**Comment by kitskub** [comment] 2012-01-03 03:38
You do know that the last time that was updated was for CB version 1060, right? I have no clue if that is the cause of the problem or not.I have to assume not. What CB and SpoutPlugin versions are you using?

**Comment by kitskub** [comment] 2012-01-03 04:16
Fixed in latest build.

**Closed as completed by kitskub** 2012-01-03 04:16 UTC
